### DiChaViT on CHAMMI dataset:
python main.py -m -cn chammi_cfg model=dichavit ++model.enable_sample=True ++model.pretrained_model_name=small tag=chammi_demo dataset=morphem70k_v2_12channels ++optimizer.params.lr=0.00004 ++model.temperature=0.07 ++train.num_epochs=60 ++train.save_model=last ++model.new_channel_inits=[zero] ++train.batch_size=64 ++eval.batch_size=256 ++train.debug=False ++eval.every_n_epochs=6 ++eval.skip_eval_first_epoch=True ++train.tps_prob=0.2 ++model.orthogonal_channel_emb_init=True ++train.extra_loss_lambda=1 ++model.proxy_loss_lambda=0.1 ++model.ortho_loss_v1_lambda=1 ++model.gamma_s=0.5 ++model.gamma_d=2 ++model.reverse_pos_pairs=True ++train.seed=2025 ++logging.wandb.run_name=C-test ++model.hcs_sampling=lowest_cosine_prob 

### DiChaViT on JUMP-CP dataset:
python main.py -m -cn jump_cp_cfg data_chunk=jump_cp_8 tag=jumpcp_demo model=dichavit ++model.patch_size=16 ++model.enable_sample=True ++model.new_channel_inits=[zero] ++model.pretrained_model_name=small ++optimizer.params.lr=0.0004 ++model.temperature=0.07 ++train.num_epochs=100 ++train.save_model=last ++train.batch_size=64 ++eval.batch_size=256 ++eval.every_n_epochs=1 ++eval.eval_subset_channels=True ++eval.skip_eval_first_epoch=True ++optimizer.params.weight_decay=0.04 ++scheduler.params.warmup_t=10 hardware=two_gpus_dp ++model.use_channelvit_channels=True ++train.extra_loss_lambda=1 ++model.proxy_loss_lambda=0.001 ++model.ortho_loss_v1_lambda=0.001 ++model.gamma_s=1 ++model.gamma_d=4 ++model.reverse_pos_pairs=True ++model.orthogonal_channel_emb_init=True ++logging.wandb.run_name=J-test ++train.seed=33978 ++model.hcs_sampling=lowest_cosine_prob ++model.hcs_sampling_temp=1000 

### DiChaViT on So2Sat 
python main.py -m -cn so2sat_city_cfg data_chunk=so2sat_city_full tag=so2sat_demo model=dichavit ++model.patch_size=8 ++model.enable_sample=True ++model.new_channel_inits=[zero] ++model.pretrained_model_name=small ++optimizer.params.lr=0.0004 ++model.temperature=0.07 ++train.num_epochs=100 ++train.save_model=last ++train.batch_size=128 ++eval.batch_size=256 ++eval.every_n_epochs=1 ++eval.eval_subset_channels=False ++eval.skip_eval_first_epoch=True ++model.use_channelvit_channels=True ++train.extra_loss_lambda=1 ++model.proxy_loss_lambda=0.001 ++model.ortho_loss_v1_lambda=0.1 ++model.gamma_s=0.5 ++model.gamma_d=4 ++model.reverse_pos_pairs=True ++model.use_channelvit_channels=True ++model.orthogonal_channel_emb_init=True ++model.hcs_sampling=lowest_cosine_prob ++train.seed=2025 ++model.hcs_sampling_temp=0.01 ++logging.wandb.run_name=S-test 
-----

### ChannelViT on CHAMMI dataset:
python main.py -m -cn chammi_cfg model=channelvit_adapt ++model.enable_sample=True ++model.pretrained_model_name=small tag=12channels dataset=morphem70k_v2_12channels ++optimizer.params.lr=0.00004 ++model.temperature=0.07 ++train.num_epochs=60 ++train.save_model=last ++model.new_channel_inits=[zero] ++train.batch_size=64 ++eval.batch_size=256 ++train.debug=False ++eval.every_n_epochs=6 ++eval.skip_eval_first_epoch=True ++train.seed=215579 ++train.tps_prob=0.2 ++logging.wandb.run_name=C-HCSchannelViT

### ChannelViT on JUMP-CP dataset:
python main.py -m -cn jump_cp_cfg data_chunk=jump_cp_8 tag=jumpcp_8 model=channelvit_adapt ++model.patch_size=16 ++model.enable_sample=True ++model.new_channel_inits=[zero] ++model.pretrained_model_name=small ++optimizer.params.lr=0.0004 ++model.temperature=0.07 ++train.num_epochs=100 ++train.save_model=last ++train.batch_size=64 ++eval.batch_size=256 ++eval.every_n_epochs=1 ++eval.eval_subset_channels=True ++optimizer.params.weight_decay=0.04 ++train.seed=831964 ++scheduler.params.warmup_t=10 hardware=two_gpus 

### ChannelViT on So2Sat dataset:
python main.py -m -cn so2sat_city_cfg data_chunk=so2sat_city_full tag=subchannels model=channelvit_adapt ++model.patch_size=8 ++model.enable_sample=True ++model.new_channel_inits=[zero] ++model.pretrained_model_name=small ++optimizer.params.lr=0.0004 ++model.temperature=0.07 ++train.num_epochs=100 ++train.save_model=last ++train.batch_size=256 ++eval.batch_size=512 ++eval.every_n_epochs=1 ++eval.eval_subset_channels=True ++eval.skip_eval_first_epoch=True ++model.use_channelvit_channels=True ++train.seed=837387 ++scheduler.params.warmup_t=10 ++logging.wandb.run_name=S-channelViT