name: depthwiseconvnext
pretrained: True
pretrained_model_name: convnext_tiny.fb_in22k  ## convnext_tiny.fb_in22k_ft_in1k, convnext_small.in12k_ft_in1k
in_dim: ~  # autofill later if None
num_classes: ~ # autofill later if None
pooling: "avg"
temperature: 0.11111
learnable_temp: False
unfreeze_last_n_layers: -1
unfreeze_first_layer: True
init_first_layer: reinit_as_random
new_channel_inits: [avg_2]
reset_last_n_unfrozen_layers: False
use_auto_rgn: False
kernels_per_channel: FILL_LATER
pooling_channel_type: FILL_LATER  # choice(sum, avg, weighted_sum_random, weighted_sum_one, weighted_sum_random_no_softmax,  weighted_sum_one_no_softmax, attention)
in_channel_names: ['er','golgi','membrane','microtubules','mito', 'nucleus', 'protein', 'rna']
enable_sample: False
patch_size: 4
reduce_size: True
sample_by_weights_scale: 0.5
sample_by_weights: False
channel_extractor_dim: 64
sample_by_weights_warmup: 0
channel_extractor_patch_size: 8