defaults:
  - train: ~
  - model: ~
  - scheduler: ~
  - optimizer: ~
  - dataset: ~
  - data_chunk: ~
  - logging: ~
  - hardware: ~
  - eval: ~
  - attn_pooling: ~
  - _self_

tag: ~

hydra:
  sweeper:
    params:
      train: random_instance
      data_chunk: so2sat_city
      model: convnext_base
      scheduler: cosine
      optimizer: adamw
      dataset: so2sat_city
      logging: wandb
      hardware: default
      eval: default
      attn_pooling: none